# https://golangci-lint.run/usage/configuration/

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  show-stats: true

linters:
  enable-all: true
  disable:
    # - deadcode
    - depguard
    - execinquery
    # - exhaustivestruct
    - exportloopref
    - gci
    - gofmt
    - gofumpt
    - goimports
    # - golint
    - gomnd
    # - ifshort
    # - interfacer
    # - maligned
    # - nosnakecase
    - paralleltest
    # - scopelint
    # - structcheck
    # - varcheck
    - wrapcheck
  # fast: true
